### YamlMime:FAQ
metadata:
  title: Preguntas frecuentes sobre la implementación centralizada
  f1.keywords:
  - NOCSH
  ms.author: kwekua
  author: kwekua
  manager: scotv
  audience: Admin
  ms.topic: faq
  ms.service: o365-administration
  ms.localizationpriority: medium
  ms.collection:
  - M365-subscription-management
  - Adm_O365
  - Adm_NonTOC
  - Adm_TOC
  ms.custom: AdminSurgePortfolio
  search.appverid:
  - BCS160
  - MET150
  - MOE150
  description: Revise las respuestas a preguntas frecuentes sobre la implementación centralizada desde el Centro de administración de Microsoft 365.
  ms.openlocfilehash: 63ccddde4a55b4842f38fb801c31fe3108e8743f
  ms.sourcegitcommit: e50c13d9be3ed05ecb156d497551acf2c9da9015
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 04/27/2022
  ms.locfileid: "65094314"
title: Preguntas frecuentes sobre la implementación centralizada
summary: La implementación centralizada es la manera recomendada para que un administrador de Office 365 implemente complementos de Office (Word, Excel, PowerPoint y Outlook) en usuarios y grupos de una organización, siempre que la organización cumpla todos los requisitos para usar la implementación centralizada, como se describe en este artículo.
sections:
- name: Ignorado
  questions:
  - question: >
      Cómo saber si mi organización está configurada para la implementación centralizada?
    answer: "La implementación centralizada de complementos requiere que los usuarios usen Aplicaciones Microsoft 365 para empresas (y inicien sesión en Office con sus credenciales de inicio de sesión de la organización) y que tengan buzones de Exchange Online. El directorio de suscripción debe estar en Azure Active Directory o estar federado en él. \n \nLa implementación centralizada solo se admite para buzones en línea. No admite la implementación en buzones de Exchange locales.\n\nPuede usar el [Comprobador de compatibilidad de implementación centralizada](centralized-deployment-of-add-ins.md#centralized-deployment-compatibility-checker) para determinar si la suscripción es apta. \n  \n"
  - question: >
      ¿Cómo se destinan las asignaciones de usuarios de complemento con la implementación centralizada?
    answer: "La implementación centralizada admite asignaciones a usuarios individuales, grupos y todos los usuarios del inquilino. La implementación centralizada se puede usar para los usuarios de grupos o grupos de nivel superior sin grupos primarios, pero no para los usuarios de grupos anidados o grupos que tienen grupos primarios. La implementación centralizada también forma parte de la mayoría de los grupos Azure Active Directory, incluidos los grupos de Office 365, las listas de distribución y los grupos de seguridad. \n\nEs mejor usar asignaciones de grupos en lugar de asignaciones de usuarios individuales para facilitar la administración.\n \nPara obtener más información, consulte [Asignaciones de usuarios y grupos](./centralized-deployment-of-add-ins.md?view=o365-worldwide#user-and-group-assignments).\n \n"
  - question: >
      ¿Cuánto tiempo tardan los complementos en aparecer para todos los usuarios?
    answer: >
      Una nueva implementación de complemento puede tardar hasta 24 horas en aparecer para todos los usuarios. Las actualizaciones de complementos, los cambios de activación o desactivación pueden tardar hasta 72 horas en reflejarse para los usuarios.
  - question: >
      Como administrador, ¿cómo puedo administrar el acceso del usuario a los complementos de mi organización?
    answer: >
      Para facilitar la implementación de complementos en usuarios, grupos o en toda la organización, se recomienda a los administradores usar la implementación centralizada.


      Para obtener más información sobre cómo administrar el acceso de los usuarios, consulte:
       - [Impedir descargas de complementos desactivando la Tienda Office en todos los clientes (excepto Outlook)](./manage-addins-in-the-admin-center.md#prevent-add-in-downloads-by-turning-off-the-office-store-across-all-clients-except-outlook)
       - [Especifique qué administradores y usuarios pueden instalar y administrar complementos para Outlook](/Exchange/specify-who-can-install-and-manage-add-ins-2013-help)
  - question: "¿Proporcionará la implementación centralizada a los administradores la flexibilidad de elegir el método de implementación para Outlook complementos? \n"
    answer: "Sí. La implementación centralizada proporciona a los administradores la flexibilidad de elegir uno de los dos métodos de implementación para Outlook complementos durante la implementación de complementos:\n         \n**Disponible** Los usuarios pueden instalar el complemento en Outlook eligiendo **Inicio > Obtener más complementos > administrados por el administrador**.\n \n**Opcional** El complemento se implementa automáticamente en los usuarios asignados, pero pueden optar por quitarlo.\n    \n"
  - question: "¿Pueden los administradores actualizar complementos de línea de negocio (LOB)? \n"
    answer: "Sí. Los administradores pueden cargar un nuevo archivo de manifiesto para admitir los cambios de metadatos de los complementos LOB implementados por el administrador. El complemento se actualiza la próxima vez que se inician las aplicaciones de Office. La aplicación web puede cambiar en cualquier momento.\n \nPara obtener más información, consulte [complemento de línea de negocio](./manage-addins-in-the-admin-center.md).  \n"
  - question: "¿Pueden los administradores desactivar los complementos? \n"
    answer: >
      Sí. Los administradores pueden activar o desactivar los complementos que implementan para todos los usuarios desde el Centro de administración de Microsoft.


      Para obtener más información, vea [Estados de complemento](./manage-addins-in-the-admin-center.md#add-in-states).
  - question: >
      ¿Pueden los administradores eliminar o quitar complementos?
    answer: "Sí. Los administradores pueden eliminar los complementos que implementaron para todos los usuarios desde el Centro de administración de Microsoft.\n\nPara obtener más información, vea [Eliminar un complemento](./manage-addins-in-the-admin-center.md#delete-an-add-in). \n  \n"
  - question: "¿Pueden los administradores implementar complementos de pago desde Office Store mediante la implementación centralizada? \n"
    answer: "No. En este momento no puede implementar complementos de pago desde Office Store mediante la implementación centralizada. \n \nSe recomienda ponerse en contacto con el desarrollador de ISV para que el complemento de pago solicite un archivo de manifiesto o una dirección URL. A continuación, el administrador de inquilinos puede implementar el complemento como un complemento de LOB mediante la implementación centralizada.\n   \n"
  - question: "¿Qué rol de administrador necesito para administrar complementos para mi organización? \n"
    answer: "Administrador global es el rol recomendado con acceso completo al ciclo de vida de administración de complementos. Si eres la persona que compró tu suscripción a Microsoft 365 Business, eres el administrador global.\n\nLa suscripción incluye un conjunto de roles de administrador que puede asignar a otros usuarios de la organización. Cada rol de administrador se asigna a funciones empresariales comunes y proporciona a los usuarios de la organización permisos para realizar tareas específicas en el Centro de administración de Microsoft 365.  \n \nPara obtener más información, consulte [Asignación de roles de administrador](../add-users/assign-admin-roles.md?view=o365-worldwide)."
